### ISSUE TITLE
Adrians Solution 

### ISSUE THREAD

**Issue by Wyatt23** [ga-wdi-exercises/tic_tac_toe#100]
Here is a link to my working respository. I am suddenly having major issues with gh-pages. Any help on getting it all back on track would be awesome. 

https://github.com/Wyatt23/TicTacToe

**Comment by amaseda** [comment]
Made a PR! Take a look at my inline code comments. No need to merge it.

https://github.com/Wyatt23/TicTacToe/pull/3
