### ISSUE TITLE
Issue Deploying Tic Tac Toe to Heroku

### ISSUE THREAD

**Issue by Dibbledl01** [ga-wdi-exercises/tic_tac_toe#104]
Hello! I'm trying to deploy my tic-tac-toe lab to Heroku to incorporate into my portfolio website.

Heroku is throwing me the following error: 

remote:  !     Push rejected, no Cedar-supported app detected
remote: HINT: This occurs when Heroku cannot detect the buildpack
remote:       to use for this application automatically.
remote: See https://devcenter.heroku.com/articles/buildpacks
remote: 
remote: Verifying deploy...
remote: 
remote: !   Push rejected to brittany-tic-tac-toe.
remote: 
To https://git.heroku.com/brittany-tic-tac-toe.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/brittany-tic-tac-toe.git'

I followed the link the error provided and read up on build packs. However, my game is a plain ole HTML/CSS/JS app. Can Heroku support this (without a formal framework)?

Here's a link to my github repo: https://github.com/Dibbledl01/tic_tac_toe

Thanks!
Brittany

**Comment by Anglinadev** [comment]
Free eclipse source tic tac toe
http://trickileaks.blogspot.com/2016/04/tic-tac-toe-for-android-source-code.html
