### ISSUE TITLE
Can't get pull request to work... link to repo here:

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/tic_tac_toe#17]
comfort_level: 4
completeness: 5

link to the new repo I created after detached head state below:
https://github.com/tomBeach/ticTacToe_2
Enclosing a screen capture of the window I get when clicking "New Pull Request" on github.com/ga-dc/tic_tac_toe (and choose_your_own_adventure)
![newpullrequestscreenshot](https://cloud.githubusercontent.com/assets/10157094/8514863/0175f532-2366-11e5-9169-e351f22ca847.jpg)

**Comment by jshawl** [comment]
You're currently comparing the master branch to the master branch, but you need to compare the master branch on your fork to the master branch on this repo - I clicked "compare across forks" and selected your name - https://github.com/ga-dc/tic_tac_toe/compare/master...tomBeach:master

**Comment by adambray** [comment]
Closing this issue, since your PR came through.
